class Settings {
  static get (key, defaultValue = null) {
    if (this.has(key)) {
      return JSON.parse(localStorage.getItem(key))
    } else if (defaultValue !== null) {
      return defaultValue
    }

    return this.getDefault(key)
  }

  static set (key, value) {
    localStorage.setItem(key, JSON.stringify(value))
  }

  static has (key) {
    return localStorage.getItem(key) !== null
  }

  static reset (key) {
    set(key, null)
  }

  static getDefault (key) {
    if (key in SettingsInternal.DEFAULT_VALUES) {
      return SettingsInternal.DEFAULT_VALUES[key]
    }

    return null
  }
}

class SettingsKeys {
  static GLOBAL_IS_ADP_ENHANCED_ENABLED =
    'ADP_ENHANCED_GLOBAL_IS_ADP_ENHANCED_ENABLED'
  static TIME_MORNING_HOURS = 'ADP_ENHANCED_TIME_MORNING_HOURS'
  static TIME_MORNING_MINUTES = 'ADP_ENHANCED_TIME_MORNING_MINUTES'
  static TIME_MORNING_HOURS = 'ADP_ENHANCED_TIME_MORNING_HOURS'
  static TIME_MORNING_MINUTES = 'ADP_ENHANCED_TIME_MORNING_MINUTES'
  static TIME_AFTERNOON_HOURS = 'ADP_ENHANCED_TIME_AFTERNOON_HOURS'
  static TIME_AFTERNOON_MINUTES = 'ADP_ENHANCED_TIME_AFTERNOON_MINUTES'
  static TIME_BEGINNING_LUNCH_BREAK_HOURS =
    'ADP_ENHANCED_TIME_BEGINNING_LUNCH_BREAK_HOURS'
  static TIME_BEGINNING_LUNCH_BREAK_MINUTES =
    'ADP_ENHANCED_TIME_BEGINNING_LUNCH_BREAK_MINUTES'
  static TIME_ENDING_LUNCH_BREAK_HOURS =
    'ADP_ENHANCED_TIME_ENDING_LUNCH_BREAK_HOURS'
  static TIME_ENDING_LUNCH_BREAK_MINUTES =
    'ADP_ENHANCED_TIME_ENDING_LUNCH_BREAK_MINUTES'
  static TIME_MINIMUM_BEGINNING_WORKING_HOURS =
    'ADP_ENHANCED_TIME_MINIMUM_BEGINNING_WORKING_HOURS'
  static TIME_MINIMUM_BEGINNING_WORKING_MINUTES =
    'ADP_ENHANCED_TIME_MINIMUM_BEGINNING_WORKING_MINUTES'
  static TIME_MINIMUM_LEAVING_WORKING_HOURS =
    'ADP_ENHANCED_TIME_MINIMUM_LEAVING_WORKING_HOURS'
  static TIME_MINIMUM_LEAVING_WORKING_MINUTES =
    'ADP_ENHANCED_TIME_MINIMUM_LEAVING_WORKING_MINUTES'
  static TIME_MAXIMUM_LEAVING_WORKING_HOURS =
    'ADP_ENHANCED_TIME_MAXIMUM_LEAVING_WORKING_HOURS'
  static TIME_MAXIMUM_LEAVING_WORKING_MINUTES =
    'ADP_ENHANCED_TIME_MAXIMUM_LEAVING_WORKING_MINUTES'
  static TIME_MINIMUM_LUNCH_BREAK_HOURS =
    'ADP_ENHANCED_TIME_MINIMUM_LUNCH_BREAK_HOURS'
  static TIME_MINIMUM_LUNCH_BREAK_MINUTES =
    'ADP_ENHANCED_TIME_MINIMUM_LUNCH_BREAK_MINUTES'
  static TIME_MORNING_BREAK_HOURS = 'ADP_ENHANCED_TIME_MORNING_BREAK_HOURS'
  static TIME_MORNING_BREAK_MINUTES = 'ADP_ENHANCED_TIME_MORNING_BREAK_MINUTES'
  static TIME_AFTERNOON_BREAK_HOURS = 'ADP_ENHANCED_TIME_AFTERNOON_BREAK_HOURS'
  static TIME_AFTERNOON_BREAK_MINUTES =
    'ADP_ENHANCED_TIME_AFTERNOON_BREAK_MINUTES'
  static TIME_MORNING_HOURS = 'ADP_ENHANCED_TIME_MORNING_HOURS'
  static TIME_AFTERNOON_HOURS = 'ADP_ENHANCED_TIME_AFTERNOON_HOURS'
  static TIME_MORNING_MINUTES = 'ADP_ENHANCED_TIME_MORNING_MINUTES'
  static TIME_AFTERNOON_MINUTES = 'ADP_ENHANCED_TIME_AFTERNOON_MINUTES'
  static TIME_RECOMMENDED_BEGINNING_WORKING_HOURS =
    'ADP_ENHANCED_TIME_RECOMMENDED_BEGINNING_WORKING_HOURS'
  static TIME_RECOMMENDED_BEGINNING_WORKING_MINUTES =
    'ADP_ENHANCED_TIME_RECOMMENDED_BEGINNING_WORKING_MINUTES'
  static TIME_RECOMMENDED_BEGINNING_LUNCH_HOURS =
    'ADP_ENHANCED_TIME_RECOMMENDED_BEGINNING_LUNCH_HOURS'
  static TIME_RECOMMENDED_BEGINNING_LUNCH_MINUTES =
    'ADP_ENHANCED_TIME_RECOMMENDED_BEGINNING_LUNCH_MINUTES'
  static TIME_RECOMMENDED_ENDING_LUNCH_HOURS =
    'ADP_ENHANCED_TIME_RECOMMENDED_ENDING_LUNCH_HOURS'
  static TIME_RECOMMENDED_ENDING_LUNCH_MINUTES =
    'ADP_ENHANCED_TIME_RECOMMENDED_ENDING_LUNCH_MINUTES'
  static TIME_RECOMMENDED_ENDING_WORKING_HOURS =
    'ADP_ENHANCED_TIME_RECOMMENDED_ENDING_WORKING_HOURS'
  static TIME_RECOMMENDED_ENDING_WORKING_MINUTES =
    'ADP_ENHANCED_TIME_RECOMMENDED_ENDING_WORKING_MINUTES'
  static TIME_RECOMMENDED_LUNCH_BREAK_HOURS =
    'ADP_ENHANCED_TIME_RECOMMENDED_LUNCH_BREAK_HOURS'
  static TIME_RECOMMENDED_LUNCH_BREAK_MINUTES =
    'ADP_ENHANCED_TIME_RECOMMENDED_LUNCH_BREAK_MINUTES'
  static TIME_LOWEST_TOTAL_EXTRA_HOURS =
    'ADP_ENHANCED_TIME_LOWEST_TOTAL_EXTRA_HOURS'
  static TIME_LOWEST_TOTAL_EXTRA_MINUTES =
    'ADP_ENHANCED_TIME_LOWEST_TOTAL_EXTRA_MINUTES'
  static TIME_HIGHEST_WEEKLY_EXTRA_HOURS =
    'ADP_ENHANCED_TIME_HIGHEST_WEEKLY_EXTRA_HOURS'
  static TIME_HIGHEST_WEEKLY_EXTRA_MINUTES =
    'ADP_ENHANCED_TIME_HIGHEST_WEEKLY_EXTRA_MINUTES'
  static TIME_HIGHEST_TOTAL_EXTRA_HOURS =
    'ADP_ENHANCED_TIME_HIGHEST_TOTAL_EXTRA_HOURS'
  static TIME_HIGHEST_TOTAL_EXTRA_MINUTES =
    'ADP_ENHANCED_TIME_HIGHEST_TOTAL_EXTRA_MINUTES'
}

class SettingsInternal {
  static DEFAULT_VALUES = {
    [SettingsKeys.GLOBAL_IS_ADP_ENHANCED_ENABLED]: true,
    [SettingsKeys.TIME_MORNING_HOURS]: 3,
    [SettingsKeys.TIME_MORNING_MINUTES]: 30,
    [SettingsKeys.TIME_AFTERNOON_HOURS]: 3,
    [SettingsKeys.TIME_AFTERNOON_MINUTES]: 30,
    [SettingsKeys.TIME_BEGINNING_LUNCH_BREAK_HOURS]: 12,
    [SettingsKeys.TIME_BEGINNING_LUNCH_BREAK_MINUTES]: 0,
    [SettingsKeys.TIME_ENDING_LUNCH_BREAK_HOURS]: 14,
    [SettingsKeys.TIME_ENDING_LUNCH_BREAK_MINUTES]: 0,
    [SettingsKeys.TIME_MINIMUM_BEGINNING_WORKING_HOURS]: 8,
    [SettingsKeys.TIME_MINIMUM_BEGINNING_WORKING_MINUTES]: 0,
    [SettingsKeys.TIME_MINIMUM_LEAVING_WORKING_HOURS]: 17,
    [SettingsKeys.TIME_MINIMUM_LEAVING_WORKING_MINUTES]: 0,
    [SettingsKeys.TIME_MAXIMUM_LEAVING_WORKING_HOURS]: 19,
    [SettingsKeys.TIME_MAXIMUM_LEAVING_WORKING_MINUTES]: 0,
    [SettingsKeys.TIME_MINIMUM_LUNCH_BREAK_HOURS]: 1,
    [SettingsKeys.TIME_MINIMUM_LUNCH_BREAK_MINUTES]: 0,
    [SettingsKeys.TIME_MORNING_BREAK_HOURS]: 0,
    [SettingsKeys.TIME_MORNING_BREAK_MINUTES]: 15,
    [SettingsKeys.TIME_AFTERNOON_BREAK_HOURS]: 0,
    [SettingsKeys.TIME_AFTERNOON_BREAK_MINUTES]: 15,
    [SettingsKeys.TIME_RECOMMENDED_BEGINNING_WORKING_HOURS]: 9,
    [SettingsKeys.TIME_RECOMMENDED_BEGINNING_WORKING_MINUTES]: 0,
    [SettingsKeys.TIME_RECOMMENDED_BEGINNING_LUNCH_HOURS]: 12,
    [SettingsKeys.TIME_RECOMMENDED_BEGINNING_LUNCH_MINUTES]: 30,
    [SettingsKeys.TIME_RECOMMENDED_ENDING_LUNCH_HOURS]: 14,
    [SettingsKeys.TIME_RECOMMENDED_ENDING_LUNCH_MINUTES]: 0,
    [SettingsKeys.TIME_RECOMMENDED_ENDING_WORKING_HOURS]: 18,
    [SettingsKeys.TIME_RECOMMENDED_ENDING_WORKING_MINUTES]: 0,
    [SettingsKeys.TIME_RECOMMENDED_LUNCH_BREAK_HOURS]: 1,
    [SettingsKeys.TIME_RECOMMENDED_LUNCH_BREAK_MINUTES]: 30,
    [SettingsKeys.TIME_LOWEST_TOTAL_EXTRA_HOURS]: -3,
    [SettingsKeys.TIME_LOWEST_TOTAL_EXTRA_MINUTES]: 0,
    [SettingsKeys.TIME_HIGHEST_WEEKLY_EXTRA_HOURS]: 3,
    [SettingsKeys.TIME_HIGHEST_WEEKLY_EXTRA_MINUTES]: 0,
    [SettingsKeys.TIME_HIGHEST_TOTAL_EXTRA_HOURS]: 10,
    [SettingsKeys.TIME_HIGHEST_TOTAL_EXTRA_MINUTES]: 0
  }
}
